[2024-01-18T02:16:47.325+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: branchtest.impar_task manual__2024-01-18T02:16:43.953684+00:00 [queued]>
[2024-01-18T02:16:47.331+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: branchtest.impar_task manual__2024-01-18T02:16:43.953684+00:00 [queued]>
[2024-01-18T02:16:47.331+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-18T02:16:47.331+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-01-18T02:16:47.331+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-18T02:16:47.339+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): impar_task> on 2024-01-18 02:16:43.953684+00:00
[2024-01-18T02:16:47.342+0000] {standard_task_runner.py:55} INFO - Started process 24056 to run task
[2024-01-18T02:16:47.344+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'branchtest', 'impar_task', 'manual__2024-01-18T02:16:43.953684+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/18-branchs.py', '--cfg-path', '/tmp/tmp8q1dvdwe']
[2024-01-18T02:16:47.345+0000] {standard_task_runner.py:83} INFO - Job 82: Subtask impar_task
[2024-01-18T02:16:47.371+0000] {task_command.py:388} INFO - Running <TaskInstance: branchtest.impar_task manual__2024-01-18T02:16:43.953684+00:00 [running]> on host 718831e78672
[2024-01-18T02:16:47.427+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=branchtest
AIRFLOW_CTX_TASK_ID=impar_task
AIRFLOW_CTX_EXECUTION_DATE=2024-01-18T02:16:43.953684+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-18T02:16:43.953684+00:00
[2024-01-18T02:16:47.430+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-01-18T02:16:47.432+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo "NÃºmero Impar']
[2024-01-18T02:16:47.449+0000] {subprocess.py:86} INFO - Output:
[2024-01-18T02:16:47.452+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: unexpected EOF while looking for matching `"'
[2024-01-18T02:16:47.452+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 2: syntax error: unexpected end of file
[2024-01-18T02:16:47.453+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-01-18T02:16:47.462+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-01-18T02:16:47.465+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=branchtest, task_id=impar_task, execution_date=20240118T021643, start_date=20240118T021647, end_date=20240118T021647
[2024-01-18T02:16:47.471+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 82 for task impar_task (Bash command failed. The command returned a non-zero exit code 2.; 24056)
[2024-01-18T02:16:47.477+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-01-18T02:16:47.489+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
