[2024-01-18T02:17:30.423+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: branchtest.impar_task manual__2024-01-18T02:17:27.034108+00:00 [queued]>
[2024-01-18T02:17:30.448+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: branchtest.impar_task manual__2024-01-18T02:17:27.034108+00:00 [queued]>
[2024-01-18T02:17:30.449+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-18T02:17:30.450+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-01-18T02:17:30.450+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-18T02:17:30.464+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): impar_task> on 2024-01-18 02:17:27.034108+00:00
[2024-01-18T02:17:30.474+0000] {standard_task_runner.py:55} INFO - Started process 24134 to run task
[2024-01-18T02:17:30.484+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'branchtest', 'impar_task', 'manual__2024-01-18T02:17:27.034108+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/18-branchs.py', '--cfg-path', '/tmp/tmpllniql50']
[2024-01-18T02:17:30.486+0000] {standard_task_runner.py:83} INFO - Job 88: Subtask impar_task
[2024-01-18T02:17:30.630+0000] {task_command.py:388} INFO - Running <TaskInstance: branchtest.impar_task manual__2024-01-18T02:17:27.034108+00:00 [running]> on host 718831e78672
[2024-01-18T02:17:30.749+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=branchtest
AIRFLOW_CTX_TASK_ID=impar_task
AIRFLOW_CTX_EXECUTION_DATE=2024-01-18T02:17:27.034108+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-18T02:17:27.034108+00:00
[2024-01-18T02:17:30.751+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-01-18T02:17:30.752+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo "NÃºmero Impar']
[2024-01-18T02:17:30.772+0000] {subprocess.py:86} INFO - Output:
[2024-01-18T02:17:30.787+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: unexpected EOF while looking for matching `"'
[2024-01-18T02:17:30.788+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 2: syntax error: unexpected end of file
[2024-01-18T02:17:30.789+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-01-18T02:17:30.833+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-01-18T02:17:30.854+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=branchtest, task_id=impar_task, execution_date=20240118T021727, start_date=20240118T021730, end_date=20240118T021730
[2024-01-18T02:17:30.896+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 88 for task impar_task (Bash command failed. The command returned a non-zero exit code 2.; 24134)
[2024-01-18T02:17:30.939+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-01-18T02:17:30.977+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
